# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - id: haws
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    main: .
    binary: haws
    goarch:
      - amd64
      - arm
      - arm64
release:
  github:
    owner: dragosboca
    name: haws

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
